Failure # 1 (occurred at 2021-10-30_19-04-06)
Traceback (most recent call last):
  File "/home/kevin/Programming_Stuff/Enter/envs/procgen_env/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 812, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/kevin/Programming_Stuff/Enter/envs/procgen_env/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 767, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/kevin/Programming_Stuff/Enter/envs/procgen_env/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "/home/kevin/Programming_Stuff/Enter/envs/procgen_env/lib/python3.8/site-packages/ray/worker.py", line 1623, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, [36mray::DQN.__init__()[39m (pid=81039, ip=10.0.10.216)
  File "/home/kevin/Programming_Stuff/Enter/envs/procgen_env/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 137, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/home/kevin/Programming_Stuff/Enter/envs/procgen_env/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 611, in __init__
    super().__init__(config, logger_creator)
  File "/home/kevin/Programming_Stuff/Enter/envs/procgen_env/lib/python3.8/site-packages/ray/tune/trainable.py", line 106, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/kevin/Programming_Stuff/Enter/envs/procgen_env/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 147, in setup
    super().setup(config)
  File "/home/kevin/Programming_Stuff/Enter/envs/procgen_env/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 764, in setup
    self._init(self.config, self.env_creator)
  File "/home/kevin/Programming_Stuff/Enter/envs/procgen_env/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 171, in _init
    self.workers = self._make_workers(
  File "/home/kevin/Programming_Stuff/Enter/envs/procgen_env/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 846, in _make_workers
    return WorkerSet(
  File "/home/kevin/Programming_Stuff/Enter/envs/procgen_env/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 103, in __init__
    self._local_worker = self._make_worker(
  File "/home/kevin/Programming_Stuff/Enter/envs/procgen_env/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 399, in _make_worker
    worker = cls(
  File "/home/kevin/Programming_Stuff/Enter/envs/procgen_env/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 569, in __init__
    raise RuntimeError(
RuntimeError: Found 0 GPUs on your machine (GPU devices found: [])! If your machine
    does not have any GPUs, you should set the config keys `num_gpus` and
    `num_gpus_per_worker` to 0 (they may be set to 1 by default for your
    particular RL algorithm).
To change the config for the `rllib train|rollout` command, use
  `--config={'[key]': '[value]'}` on the command line.
To change the config for `tune.run()` in a script: Modify the python dict
  passed to `tune.run(config=[...])`.
To change the config for an RLlib Trainer instance: Modify the python dict
  passed to the Trainer's constructor, e.g. `PPOTrainer(config=[...])`.

